### ISSUE TITLE
Minify sources

### ISSUE THREAD

**Issue by joewiz** [eXist-db/existdb-dashboard#1]
The old dashboard is 574 KB. The new dashboard weighs in at 8.2 MB.

**Comment by adamretter** [comment]
I just ran the build process as documented in the `README.md` - perhaps it is not up to date?

**Comment by JoernT** [comment]
have fixed that locally but can't push my changes at the moment due to github auth problems

**Comment by JoernT** [comment]
fixed in 1.0.1

**Comment by joewiz** [comment]
Confirmed that 1.2.2's xar is now 573k:

> <img width="520" alt="screen shot 2018-10-10 at 12 09 40 pm" src="https://user-images.githubusercontent.com/59118/46750223-7b879580-cc85-11e8-9b30-2808c5c8a6ad.png">
