### ISSUE TITLE
Group managers are missing from the group and user views

### ISSUE THREAD

**Issue by adamretter** [eXist-db/existdb-dashboard#10]

**Comment by JoernT** [comment]
may well be my lack of understanding but i can't see something like a group manager for users when i take the java admin client as reference.

For groups please see the checkbox 'is Manager' on the right of the list. This however seems to have a bug not displaying the right state. In my case when i select 'dba' group the group manager flag is set for 'admin' in the Java admin client but not in usermanager. This is something i can look after.

**Comment by adamretter** [comment]
@JoernT Group Manager in the Java Admin Client:

<img width="828" alt="screenshot 2019-01-08 at 18 51 58" src="https://user-images.githubusercontent.com/1264057/50826476-b11c4780-1376-11e9-9089-2d45682faba3.png">

**Comment by JoernT** [comment]
yes - saw that but that's groups right? Ticket title indicates that the same is true for users? Can't see that - however noticed that entries may be bold type in such cases? So probably this shall be the indicator here?

**Comment by adamretter** [comment]
The ticket is about managers of groups.

A group has members, each member is a user. A member of a group may also be flagged as a group manager.

A group manager has permission to add and remove members from a group without being a DBA.

1. So for a user, you would show which groups they are a member of, and if they are a manager of the group.

2. For a group, you would show the users which are members of the group, and which of those users is a manger of the group.

Hope that makes more sense now?

**Comment by JoernT** [comment]
yep - makes sense. My confusion came from the fact that the current user manager in admin client just shows the group manager status for users as a bold entry in the group list (when being in 'edit user')

**Comment by ghost** [comment]
This issue was moved by [joewiz](https://github.com/joewiz) to [eXist-db/dashboard#77](https://github.com/eXist-db/dashboard/issues/77).
