### ISSUE TITLE
Restore app name to be “dashboard” so links don’t break

### ISSUE THREAD

**Issue by joewiz** [eXist-db/existdb-dashboard#13]
Showstopper for inclusion in eXist 5.0.0-RC. See https://github.com/eXist-db/exist/pull/2408.

**Comment by adamretter** [comment]
My proposal would be to take the code history from here and append it to the `dashboard` repo, then close this repo.

**Comment by duncdrum** [comment]
@adamretter yes but for the imminent release the new dashboard is going to the RC, not stable, so we need to make sure that we can still get the old one for the `4.x` series.

**Comment by joewiz** [comment]
Migrating git repos is a slightly different issue that doesn't address the issue of URL compatibility (see #14 which does fix that), so I've opened a separate issue for that: https://github.com/eXist-db/existdb-dashboard/issues/15.
