### ISSUE TITLE
Landing page experience and eXist branding

### ISSUE THREAD

**Issue by joewiz** [eXist-db/existdb-dashboard#2]
The landing page of the new Dashboard app has no eXist branding - just the title "Launcher" with a rocket ship icon:

> <img width="830" alt="screen shot 2018-06-11 at 10 44 39 pm" src="https://user-images.githubusercontent.com/59118/41267311-0ecd8500-6dc9-11e8-991d-b989f4fc3408.png">

Contrast with the landing page of the "old" dashboard, which displays the eXist logo:

> <img width="700" alt="screen shot 2018-06-11 at 10 46 21 pm" src="https://user-images.githubusercontent.com/59118/41267389-52ce9e2e-6dc9-11e8-9f72-878f1343f492.png">

Only after logging into the new app with a dba account does the user see eXist branding (and discover that "Launcher" is simply the name of one of the Dashboard's panes):

> <img width="829" alt="screen shot 2018-06-11 at 10 45 31 pm" src="https://user-images.githubusercontent.com/59118/41267351-2de50242-6dc9-11e8-9533-bfb06b8fd3a5.png">

This screen is great, but only registered users see it. New users reaching the "Launcher" page for the first time might be lost. 

As we prepare to make this app that default landing page for eXist, is there some way we can highlight the eXist branding upon initial launch? 

Proposal:

Include the left sidebar with the "eXist-db" logo and the "Dashboard" name. Either omit the admin-only entries until you log in, or show all the entries by default (the behavior of the old dashboard - clicking on an admin-only one prompted you to log in).

**Comment by adamretter** [comment]
Also please ensure that the version number (of eXist-db) is prominent (probably under the logo) <- even when not logged in!

**Comment by JoernT** [comment]
@joewiz yes, you're right. Branding is missing. However i don't like to go back to the state where people see all apps even when not logged in. First the 'dynamic' login via ajax created some problems in the past and it requires significant changes. Second it contradict the security principle to not expose what you're not allowed to see. Even the information that there are these additional apps should not be exposed.

I would prefer a solution that works with the Launcher itself (remember that this apps might be installed standalone with no dashboad app installed at all).

However i have no idea at the moment how to do it right now - will have to think about it. Certainly we can display the exist icon (e.g. bottom right corner). It's question how big (prominent) it should be.

**Comment by joewiz** [comment]
Would the idea above to omit the admin-only sidebar entries until you log in achieve that goal? Alternatively, add a “logo” block to the launcher?

**Comment by JoernT** [comment]
@joewiz yes sure we can omit the entries but that would look really dull. Yes, maybe a logo block - problem with any of those solutions is that there are always 2 situations - running standalone or running embedded - in the latter case the logo should be hidden. Otherwise we have 2 logos - which is as bad as having none. Certainly solveable but need to play...

**Comment by JoernT** [comment]
i've gone with the additional block as was in the old dashboard to display the logo and current version of eXist-db. This is already implemented but not released yet. Will be ready soon.

The logo block is not shown if launcher is embedded in dashboard as the logo is already present.

**Comment by JoernT** [comment]
new launcher version 1.2.0 now shows logo and version and is already available. Changes become available in dashboard with next release.

**Comment by JoernT** [comment]
note to myself:
optimized version of existdb-dashboard is not showing the version information. Works in non-optimized version

**Comment by JoernT** [comment]
addressed in 1.2.0
