### ISSUE TITLE
404 when requesting an admin page after restarting eXist

### ISSUE THREAD

**Issue by joewiz** [eXist-db/existdb-dashboard#3]
I keep a tab open to the Dashboard, e.g., <http://localhost:8080/exist/apps/existdb-dashboard/admin#/launcher>. When I restart eXist, go to this tab, and reload, I get a 404 error:

> HTTP ERROR 404
> Problem accessing /exist/apps/existdb-dashboard/admin. Reason:
> Document /db/apps/existdb-dashboard/admin not found
> Powered by Jetty:// 9.4.10.v20180503

The page should at least return a 401 Unauthorized. Ideally, it would would prompt me to log in. Would this smoother load-on-relaunch flow be possible?

**Comment by ghost** [comment]
Hmhm. I get an 404 Error when opening Dashboard, without further notes  ... 
(posted it in exist, as I am unable to launch any exist-db related tools, besides configuration

**Comment by duncdrum** [comment]
@kev1807 are you using the new dashboard, what version and in what exist version?

**Comment by ghost** [comment]
Hi there, 
It basically is the I can't run exist as a service - problem. When uninstalling the Service it works perfectly.
(but I use dashboard 1.1.0 and exist 4.3.1) ( and I had to reinstall lately, since my machine crashed)

**Comment by joewiz** [comment]
@kev1807 I think you're describing a different issue than the one described here. I'd suggest posting an email to the [exist-open mailing list](https://sourceforge.net/projects/exist/lists/exist-open) with your situation and requesting help there. (As far as I know, https://github.com/eXist-db/exist/issues/2005, which was included in 4.3.1, should have fixed the problem with installing eXist as a service on Windows.)

**Comment by JoernT** [comment]
@joewiz just tested this on my mac with Chrome 69.0.3497.100  (latest) and FF 62.0.3 and works for me. I get redirected to login page.

**Comment by joewiz** [comment]
@JoernT Great, same with my testing now.
