### ISSUE TITLE
404 for backup.xql when opening backup pane

### ISSUE THREAD

**Issue by joewiz** [eXist-db/existdb-dashboard#5]
With v1.2.0 (installed via public repo), loading http://localhost:8080/exist/apps/existdb-dashboard/admin#/backup opens a request for http://localhost:8080/exist/apps/existdb-dashboard/bower_components/existdb-backup/modules/backup.xql, which returns a 404. I confirmed this resource is not present in http://demo.exist-db.org/exist/apps/public-repo/public/existdb-dashboard-1.2.0-prod.xar.

**Comment by JoernT** [comment]
build.xml needed update too for production build
